export const TOPICS = [
  "A simple understanding of Computer",
  "Issues in Computer Design",
  "Computer System Level Hierarchy",
  "Computer Architecture and Computer Organization",
  "Basic Computer Instructions",
  "Timing diagram of MOV Instruction in Microprocessor",
  "Assembly language and High level language",
  "Addressing Modes",
  "Memory based Vs Register based addressing modes",
  "Von Neumann architecture",
  "Harvard Architecture",
  "Interaction of a Program with Hardware",
  "Simplified Instructional Computer (SIC)",
  "Instruction Set used in simplified instructional Computer (SIC)",
  "Instruction Set used in SIC/XE",
  "RISC and CISC",
  "RISC and CISC | Set 2",
  "Vector processor classification",
  "Essential Registers for Instruction Execution",
  "Single Accumulator based CPU organization",
  "Stack based CPU Organization",
  "General Register based CPU Organization",
  "Data Transfer instructions in AVR microcontroller",
  "Arithmetic instructions in AVR microcontroller",
  "Conditional Branch Instructions in AVR Microcontroller",
  "CALL Instructions and Stack in AVR Microcontroller",
  "Branch Instructions in AVR Microcontroller",
  "Logical Instructions in AVR Microcontroller",
  "Data Manipulation Instructions",
  "Machine Control Instruction",
  "Very Long Instruction Word (VLIW) Architecture",
  "Different Instruction Cycles",
  "Essential Registers for Instruction Execution",
  "Machine Instructions",
  "Instruction Formats (Zero, One, Two and Three Address Instruction)",
  "2-address instruction and 1-address instructions",
  "3-address instruction and 0-address instruction",
  "3-address instruction and 2-address instructions",
  "Register content and Flag status after Instructions",
  "Debugging a machine level program",
  "Vector Instruction Format",
  "Vector instruction types",
  "Branch Prediction in Pentium",
  "Instruction Word Size",
  "Problem Solving on Instruction Format",
  "Computer Arithmetic | ALU and Data Path",
  "Computer Arithmetic | Set 1",
  "Computer Arithmetic | Set 2",
  "Difference between 1’s complement and 2’s complement",
  "Restoring Division Algorithm For Unsigned Integer",
  "Non-Restoring Division For Unsigned Integer",
  "Booth’s Algorithm",
  "Overflow in Arithmetic Addition",
  "How the negative numbers are stored in memory",
  "Conventional Computing vs Quantum Computing",
];
